//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_ADR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR_Criticality_Helper_Parameters
    {
        public ADR_Criticality_Helper_Parameters()
        {
            this.ADR_Criticality_Helper = new HashSet<ADR_Criticality_Helper>();
            this.ADR_Criticality_MesureParade = new HashSet<ADR_Criticality_MesureParade>();
        }
    
        public int Id { get; set; }
        public string ItemText { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ICollection<ADR_Criticality_Helper> ADR_Criticality_Helper { get; set; }
        public virtual ICollection<ADR_Criticality_MesureParade> ADR_Criticality_MesureParade { get; set; }
    }
}
