//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_ADR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR_Criticality_MesureParade
    {
        public int Id { get; set; }
        public string ItemText { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CriticalityRiskId { get; set; }
        public bool IsDisabled { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int WorkCenterId { get; set; }
    
        public virtual ADR_Criticality_Helper_Parameters ADR_Criticality_Helper_Parameters { get; set; }
        public virtual ADR_WorkCenter ADR_WorkCenter { get; set; }
    }
}
