//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_ADR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR_Criticality_Helper
    {
        public ADR_Criticality_Helper()
        {
            this.ADR_Criticality = new HashSet<ADR_Criticality>();
        }
    
        public int Id { get; set; }
        public int DescriptionId { get; set; }
        public string ItemText { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreateBy { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ICollection<ADR_Criticality> ADR_Criticality { get; set; }
        public virtual ADR_Criticality_Helper_Parameters ADR_Criticality_Helper_Parameters { get; set; }
    }
}
