//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_ADR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR_WorkCenterUser
    {
        public int Id { get; set; }
        public int WorkCenterId { get; set; }
        public string UserId { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ADR_WorkCenter ADR_WorkCenter { get; set; }
    }
}
