//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_ADR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR_Analysis_Parameters
    {
        public int Id { get; set; }
        public string ParameterText { get; set; }
        public int OrderCrit { get; set; }
        public int CriticalityId { get; set; }
        public bool IsNA { get; set; }
        public Nullable<int> AnalysisId { get; set; }
    
        public virtual ADR_Criticality ADR_Criticality { get; set; }
        public virtual ADR_Analysis_Result ADR_Analysis_Result { get; set; }
    }
}
