//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Control", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SynapseStatistics.Synapse_Security_Control), "Synapse_Security_Profile_Control", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SynapseStatistics.Synapse_Security_Profile_Control), true)]
[assembly: EdmRelationshipAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SynapseStatistics.Synapse_Security_Profile), "Synapse_Security_Profile_Control", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SynapseStatistics.Synapse_Security_Profile_Control), true)]
[assembly: EdmRelationshipAttribute("SYNAPSEModel", "FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SynapseStatistics.Synapse_Security_Profile), "Synapse_Security_User_Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SynapseStatistics.Synapse_Security_User_Profile), true)]
[assembly: EdmRelationshipAttribute("SYNAPSEModel", "FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SynapseStatistics.Synapse_Security_User), "Synapse_Security_User_Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SynapseStatistics.Synapse_Security_User_Profile), true)]
[assembly: EdmRelationshipAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Module", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SynapseStatistics.Synapse_Module), "Synapse_Security_Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SynapseStatistics.Synapse_Security_Profile), true)]

#endregion

namespace SynapseStatistics
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StatDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StatDataEntities object using the connection string found in the 'StatDataEntities' section of the application configuration file.
        /// </summary>
        public StatDataEntities() : base("name=StatDataEntities", "StatDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StatDataEntities object.
        /// </summary>
        public StatDataEntities(string connectionString) : base(connectionString, "StatDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StatDataEntities object.
        /// </summary>
        public StatDataEntities(EntityConnection connection) : base(connection, "StatDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Security_Control> Synapse_Security_Control
        {
            get
            {
                if ((_Synapse_Security_Control == null))
                {
                    _Synapse_Security_Control = base.CreateObjectSet<Synapse_Security_Control>("Synapse_Security_Control");
                }
                return _Synapse_Security_Control;
            }
        }
        private ObjectSet<Synapse_Security_Control> _Synapse_Security_Control;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Security_Profile> Synapse_Security_Profile
        {
            get
            {
                if ((_Synapse_Security_Profile == null))
                {
                    _Synapse_Security_Profile = base.CreateObjectSet<Synapse_Security_Profile>("Synapse_Security_Profile");
                }
                return _Synapse_Security_Profile;
            }
        }
        private ObjectSet<Synapse_Security_Profile> _Synapse_Security_Profile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Security_Profile_Control> Synapse_Security_Profile_Control
        {
            get
            {
                if ((_Synapse_Security_Profile_Control == null))
                {
                    _Synapse_Security_Profile_Control = base.CreateObjectSet<Synapse_Security_Profile_Control>("Synapse_Security_Profile_Control");
                }
                return _Synapse_Security_Profile_Control;
            }
        }
        private ObjectSet<Synapse_Security_Profile_Control> _Synapse_Security_Profile_Control;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Security_User> Synapse_Security_User
        {
            get
            {
                if ((_Synapse_Security_User == null))
                {
                    _Synapse_Security_User = base.CreateObjectSet<Synapse_Security_User>("Synapse_Security_User");
                }
                return _Synapse_Security_User;
            }
        }
        private ObjectSet<Synapse_Security_User> _Synapse_Security_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Security_User_Profile> Synapse_Security_User_Profile
        {
            get
            {
                if ((_Synapse_Security_User_Profile == null))
                {
                    _Synapse_Security_User_Profile = base.CreateObjectSet<Synapse_Security_User_Profile>("Synapse_Security_User_Profile");
                }
                return _Synapse_Security_User_Profile;
            }
        }
        private ObjectSet<Synapse_Security_User_Profile> _Synapse_Security_User_Profile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Statistics> Synapse_Statistics
        {
            get
            {
                if ((_Synapse_Statistics == null))
                {
                    _Synapse_Statistics = base.CreateObjectSet<Synapse_Statistics>("Synapse_Statistics");
                }
                return _Synapse_Statistics;
            }
        }
        private ObjectSet<Synapse_Statistics> _Synapse_Statistics;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Module> Synapse_Module
        {
            get
            {
                if ((_Synapse_Module == null))
                {
                    _Synapse_Module = base.CreateObjectSet<Synapse_Module>("Synapse_Module");
                }
                return _Synapse_Module;
            }
        }
        private ObjectSet<Synapse_Module> _Synapse_Module;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Security_Control EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Security_Control(Synapse_Security_Control synapse_Security_Control)
        {
            base.AddObject("Synapse_Security_Control", synapse_Security_Control);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Security_Profile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Security_Profile(Synapse_Security_Profile synapse_Security_Profile)
        {
            base.AddObject("Synapse_Security_Profile", synapse_Security_Profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Security_Profile_Control EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Security_Profile_Control(Synapse_Security_Profile_Control synapse_Security_Profile_Control)
        {
            base.AddObject("Synapse_Security_Profile_Control", synapse_Security_Profile_Control);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Security_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Security_User(Synapse_Security_User synapse_Security_User)
        {
            base.AddObject("Synapse_Security_User", synapse_Security_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Security_User_Profile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Security_User_Profile(Synapse_Security_User_Profile synapse_Security_User_Profile)
        {
            base.AddObject("Synapse_Security_User_Profile", synapse_Security_User_Profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Statistics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Statistics(Synapse_Statistics synapse_Statistics)
        {
            base.AddObject("Synapse_Statistics", synapse_Statistics);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Module EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Module(Synapse_Module synapse_Module)
        {
            base.AddObject("Synapse_Module", synapse_Module);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Module object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="pATH">Initial value of the PATH property.</param>
        /// <param name="tECHNICALNAME">Initial value of the TECHNICALNAME property.</param>
        /// <param name="mODULECATEGORY">Initial value of the MODULECATEGORY property.</param>
        public static Synapse_Module CreateSynapse_Module(global::System.Int64 id, global::System.String pATH, global::System.String tECHNICALNAME, global::System.String mODULECATEGORY)
        {
            Synapse_Module synapse_Module = new Synapse_Module();
            synapse_Module.ID = id;
            synapse_Module.PATH = pATH;
            synapse_Module.TECHNICALNAME = tECHNICALNAME;
            synapse_Module.MODULECATEGORY = mODULECATEGORY;
            return synapse_Module;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LABELID
        {
            get
            {
                return _LABELID;
            }
            set
            {
                OnLABELIDChanging(value);
                ReportPropertyChanging("LABELID");
                _LABELID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LABELID");
                OnLABELIDChanged();
            }
        }
        private Nullable<global::System.Int64> _LABELID;
        partial void OnLABELIDChanging(Nullable<global::System.Int64> value);
        partial void OnLABELIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PATH
        {
            get
            {
                return _PATH;
            }
            set
            {
                OnPATHChanging(value);
                ReportPropertyChanging("PATH");
                _PATH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PATH");
                OnPATHChanged();
            }
        }
        private global::System.String _PATH;
        partial void OnPATHChanging(global::System.String value);
        partial void OnPATHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TECHNICALNAME
        {
            get
            {
                return _TECHNICALNAME;
            }
            set
            {
                OnTECHNICALNAMEChanging(value);
                ReportPropertyChanging("TECHNICALNAME");
                _TECHNICALNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TECHNICALNAME");
                OnTECHNICALNAMEChanged();
            }
        }
        private global::System.String _TECHNICALNAME;
        partial void OnTECHNICALNAMEChanging(global::System.String value);
        partial void OnTECHNICALNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION
        {
            get
            {
                return _VERSION;
            }
            set
            {
                OnVERSIONChanging(value);
                ReportPropertyChanging("VERSION");
                _VERSION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION");
                OnVERSIONChanged();
            }
        }
        private global::System.String _VERSION;
        partial void OnVERSIONChanging(global::System.String value);
        partial void OnVERSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MODULECATEGORY
        {
            get
            {
                return _MODULECATEGORY;
            }
            set
            {
                OnMODULECATEGORYChanging(value);
                ReportPropertyChanging("MODULECATEGORY");
                _MODULECATEGORY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MODULECATEGORY");
                OnMODULECATEGORYChanged();
            }
        }
        private global::System.String _MODULECATEGORY;
        partial void OnMODULECATEGORYChanging(global::System.String value);
        partial void OnMODULECATEGORYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSIONDATE
        {
            get
            {
                return _VERSIONDATE;
            }
            set
            {
                OnVERSIONDATEChanging(value);
                ReportPropertyChanging("VERSIONDATE");
                _VERSIONDATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSIONDATE");
                OnVERSIONDATEChanged();
            }
        }
        private global::System.String _VERSIONDATE;
        partial void OnVERSIONDATEChanging(global::System.String value);
        partial void OnVERSIONDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DESCLABELID
        {
            get
            {
                return _DESCLABELID;
            }
            set
            {
                OnDESCLABELIDChanging(value);
                ReportPropertyChanging("DESCLABELID");
                _DESCLABELID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DESCLABELID");
                OnDESCLABELIDChanged();
            }
        }
        private Nullable<global::System.Int64> _DESCLABELID;
        partial void OnDESCLABELIDChanging(Nullable<global::System.Int64> value);
        partial void OnDESCLABELIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEVSOURCE
        {
            get
            {
                return _DEVSOURCE;
            }
            set
            {
                OnDEVSOURCEChanging(value);
                ReportPropertyChanging("DEVSOURCE");
                _DEVSOURCE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEVSOURCE");
                OnDEVSOURCEChanged();
            }
        }
        private global::System.String _DEVSOURCE;
        partial void OnDEVSOURCEChanging(global::System.String value);
        partial void OnDEVSOURCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRODSOURCE
        {
            get
            {
                return _PRODSOURCE;
            }
            set
            {
                OnPRODSOURCEChanging(value);
                ReportPropertyChanging("PRODSOURCE");
                _PRODSOURCE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRODSOURCE");
                OnPRODSOURCEChanged();
            }
        }
        private global::System.String _PRODSOURCE;
        partial void OnPRODSOURCEChanging(global::System.String value);
        partial void OnPRODSOURCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IS_ACTIVE
        {
            get
            {
                return _IS_ACTIVE;
            }
            set
            {
                OnIS_ACTIVEChanging(value);
                ReportPropertyChanging("IS_ACTIVE");
                _IS_ACTIVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_ACTIVE");
                OnIS_ACTIVEChanged();
            }
        }
        private Nullable<global::System.Boolean> _IS_ACTIVE;
        partial void OnIS_ACTIVEChanging(Nullable<global::System.Boolean> value);
        partial void OnIS_ACTIVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IS_REQUESTABLE
        {
            get
            {
                return _IS_REQUESTABLE;
            }
            set
            {
                OnIS_REQUESTABLEChanging(value);
                ReportPropertyChanging("IS_REQUESTABLE");
                _IS_REQUESTABLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_REQUESTABLE");
                OnIS_REQUESTABLEChanged();
            }
        }
        private Nullable<global::System.Boolean> _IS_REQUESTABLE;
        partial void OnIS_REQUESTABLEChanging(Nullable<global::System.Boolean> value);
        partial void OnIS_REQUESTABLEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Security_Profile")]
        public EntityCollection<Synapse_Security_Profile> Synapse_Security_Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Security_Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Security_Profile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Security_Control")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Security_Control : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Security_Control object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fORM_NAME">Initial value of the FORM_NAME property.</param>
        /// <param name="cTRL_TYPE">Initial value of the CTRL_TYPE property.</param>
        /// <param name="cTRL_NAME">Initial value of the CTRL_NAME property.</param>
        /// <param name="fK_MODULE_ID">Initial value of the FK_MODULE_ID property.</param>
        public static Synapse_Security_Control CreateSynapse_Security_Control(global::System.Int64 id, global::System.String fORM_NAME, global::System.String cTRL_TYPE, global::System.String cTRL_NAME, global::System.Int64 fK_MODULE_ID)
        {
            Synapse_Security_Control synapse_Security_Control = new Synapse_Security_Control();
            synapse_Security_Control.ID = id;
            synapse_Security_Control.FORM_NAME = fORM_NAME;
            synapse_Security_Control.CTRL_TYPE = cTRL_TYPE;
            synapse_Security_Control.CTRL_NAME = cTRL_NAME;
            synapse_Security_Control.FK_MODULE_ID = fK_MODULE_ID;
            return synapse_Security_Control;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FORM_NAME
        {
            get
            {
                return _FORM_NAME;
            }
            set
            {
                OnFORM_NAMEChanging(value);
                ReportPropertyChanging("FORM_NAME");
                _FORM_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FORM_NAME");
                OnFORM_NAMEChanged();
            }
        }
        private global::System.String _FORM_NAME;
        partial void OnFORM_NAMEChanging(global::System.String value);
        partial void OnFORM_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CTRL_TYPE
        {
            get
            {
                return _CTRL_TYPE;
            }
            set
            {
                OnCTRL_TYPEChanging(value);
                ReportPropertyChanging("CTRL_TYPE");
                _CTRL_TYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CTRL_TYPE");
                OnCTRL_TYPEChanged();
            }
        }
        private global::System.String _CTRL_TYPE;
        partial void OnCTRL_TYPEChanging(global::System.String value);
        partial void OnCTRL_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CTRL_NAME
        {
            get
            {
                return _CTRL_NAME;
            }
            set
            {
                OnCTRL_NAMEChanging(value);
                ReportPropertyChanging("CTRL_NAME");
                _CTRL_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CTRL_NAME");
                OnCTRL_NAMEChanged();
            }
        }
        private global::System.String _CTRL_NAME;
        partial void OnCTRL_NAMEChanging(global::System.String value);
        partial void OnCTRL_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_MODULE_ID
        {
            get
            {
                return _FK_MODULE_ID;
            }
            set
            {
                OnFK_MODULE_IDChanging(value);
                ReportPropertyChanging("FK_MODULE_ID");
                _FK_MODULE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_MODULE_ID");
                OnFK_MODULE_IDChanged();
            }
        }
        private global::System.Int64 _FK_MODULE_ID;
        partial void OnFK_MODULE_IDChanging(global::System.Int64 value);
        partial void OnFK_MODULE_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Profile_Control")]
        public EntityCollection<Synapse_Security_Profile_Control> Synapse_Security_Profile_Control
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Synapse_Security_Profile_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Profile_Control");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Synapse_Security_Profile_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Profile_Control", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Security_Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Security_Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Security_Profile object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fK_MODULEID">Initial value of the FK_MODULEID property.</param>
        /// <param name="iS_OWNER">Initial value of the IS_OWNER property.</param>
        /// <param name="lEVEL">Initial value of the LEVEL property.</param>
        public static Synapse_Security_Profile CreateSynapse_Security_Profile(global::System.Int64 id, global::System.Int64 fK_MODULEID, global::System.Boolean iS_OWNER, global::System.Int64 lEVEL)
        {
            Synapse_Security_Profile synapse_Security_Profile = new Synapse_Security_Profile();
            synapse_Security_Profile.ID = id;
            synapse_Security_Profile.FK_MODULEID = fK_MODULEID;
            synapse_Security_Profile.IS_OWNER = iS_OWNER;
            synapse_Security_Profile.LEVEL = lEVEL;
            return synapse_Security_Profile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_MODULEID
        {
            get
            {
                return _FK_MODULEID;
            }
            set
            {
                OnFK_MODULEIDChanging(value);
                ReportPropertyChanging("FK_MODULEID");
                _FK_MODULEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_MODULEID");
                OnFK_MODULEIDChanged();
            }
        }
        private global::System.Int64 _FK_MODULEID;
        partial void OnFK_MODULEIDChanging(global::System.Int64 value);
        partial void OnFK_MODULEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FK_LABELID
        {
            get
            {
                return _FK_LABELID;
            }
            set
            {
                OnFK_LABELIDChanging(value);
                ReportPropertyChanging("FK_LABELID");
                _FK_LABELID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_LABELID");
                OnFK_LABELIDChanged();
            }
        }
        private Nullable<global::System.Int64> _FK_LABELID;
        partial void OnFK_LABELIDChanging(Nullable<global::System.Int64> value);
        partial void OnFK_LABELIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TECHNICALNAME
        {
            get
            {
                return _TECHNICALNAME;
            }
            set
            {
                OnTECHNICALNAMEChanging(value);
                ReportPropertyChanging("TECHNICALNAME");
                _TECHNICALNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TECHNICALNAME");
                OnTECHNICALNAMEChanged();
            }
        }
        private global::System.String _TECHNICALNAME;
        partial void OnTECHNICALNAMEChanging(global::System.String value);
        partial void OnTECHNICALNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IS_OWNER
        {
            get
            {
                return _IS_OWNER;
            }
            set
            {
                OnIS_OWNERChanging(value);
                ReportPropertyChanging("IS_OWNER");
                _IS_OWNER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_OWNER");
                OnIS_OWNERChanged();
            }
        }
        private global::System.Boolean _IS_OWNER;
        partial void OnIS_OWNERChanging(global::System.Boolean value);
        partial void OnIS_OWNERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 LEVEL
        {
            get
            {
                return _LEVEL;
            }
            set
            {
                OnLEVELChanging(value);
                ReportPropertyChanging("LEVEL");
                _LEVEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LEVEL");
                OnLEVELChanged();
            }
        }
        private global::System.Int64 _LEVEL;
        partial void OnLEVELChanging(global::System.Int64 value);
        partial void OnLEVELChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile_Control")]
        public EntityCollection<Synapse_Security_Profile_Control> Synapse_Security_Profile_Control
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Synapse_Security_Profile_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile_Control");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Synapse_Security_Profile_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile_Control", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_User_Profile")]
        public EntityCollection<Synapse_Security_User_Profile> Synapse_Security_User_Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Synapse_Security_User_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_User_Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Synapse_Security_User_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_User_Profile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Module")]
        public Synapse_Module Synapse_Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Module>("SYNAPSEModel.FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Module").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Module>("SYNAPSEModel.FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Module").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Synapse_Module> Synapse_ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Module>("SYNAPSEModel.FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Synapse_Module>("SYNAPSEModel.FK_Synapse_Security_Profile_Synapse_Module", "Synapse_Module", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Security_Profile_Control")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Security_Profile_Control : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Security_Profile_Control object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fK_PROFILEID">Initial value of the FK_PROFILEID property.</param>
        /// <param name="fK_CONTROLID">Initial value of the FK_CONTROLID property.</param>
        /// <param name="iS_VISIBLE">Initial value of the IS_VISIBLE property.</param>
        /// <param name="iS_ACTIVE">Initial value of the IS_ACTIVE property.</param>
        public static Synapse_Security_Profile_Control CreateSynapse_Security_Profile_Control(global::System.Int64 id, global::System.Int64 fK_PROFILEID, global::System.Int64 fK_CONTROLID, global::System.Boolean iS_VISIBLE, global::System.Boolean iS_ACTIVE)
        {
            Synapse_Security_Profile_Control synapse_Security_Profile_Control = new Synapse_Security_Profile_Control();
            synapse_Security_Profile_Control.ID = id;
            synapse_Security_Profile_Control.FK_PROFILEID = fK_PROFILEID;
            synapse_Security_Profile_Control.FK_CONTROLID = fK_CONTROLID;
            synapse_Security_Profile_Control.IS_VISIBLE = iS_VISIBLE;
            synapse_Security_Profile_Control.IS_ACTIVE = iS_ACTIVE;
            return synapse_Security_Profile_Control;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_PROFILEID
        {
            get
            {
                return _FK_PROFILEID;
            }
            set
            {
                OnFK_PROFILEIDChanging(value);
                ReportPropertyChanging("FK_PROFILEID");
                _FK_PROFILEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_PROFILEID");
                OnFK_PROFILEIDChanged();
            }
        }
        private global::System.Int64 _FK_PROFILEID;
        partial void OnFK_PROFILEIDChanging(global::System.Int64 value);
        partial void OnFK_PROFILEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_CONTROLID
        {
            get
            {
                return _FK_CONTROLID;
            }
            set
            {
                OnFK_CONTROLIDChanging(value);
                ReportPropertyChanging("FK_CONTROLID");
                _FK_CONTROLID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_CONTROLID");
                OnFK_CONTROLIDChanged();
            }
        }
        private global::System.Int64 _FK_CONTROLID;
        partial void OnFK_CONTROLIDChanging(global::System.Int64 value);
        partial void OnFK_CONTROLIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IS_VISIBLE
        {
            get
            {
                return _IS_VISIBLE;
            }
            set
            {
                OnIS_VISIBLEChanging(value);
                ReportPropertyChanging("IS_VISIBLE");
                _IS_VISIBLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_VISIBLE");
                OnIS_VISIBLEChanged();
            }
        }
        private global::System.Boolean _IS_VISIBLE;
        partial void OnIS_VISIBLEChanging(global::System.Boolean value);
        partial void OnIS_VISIBLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IS_ACTIVE
        {
            get
            {
                return _IS_ACTIVE;
            }
            set
            {
                OnIS_ACTIVEChanging(value);
                ReportPropertyChanging("IS_ACTIVE");
                _IS_ACTIVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_ACTIVE");
                OnIS_ACTIVEChanged();
            }
        }
        private global::System.Boolean _IS_ACTIVE;
        partial void OnIS_ACTIVEChanging(global::System.Boolean value);
        partial void OnIS_ACTIVEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Control")]
        public Synapse_Security_Control Synapse_Security_Control
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Control").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Control").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Synapse_Security_Control> Synapse_Security_ControlReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Control");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Synapse_Security_Control>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Control", "Synapse_Security_Control", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile")]
        public Synapse_Security_Profile Synapse_Security_Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Synapse_Security_Profile> Synapse_Security_ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_Profile_Control_Synapse_Security_Profile", "Synapse_Security_Profile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Security_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Security_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Security_User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="uSERID">Initial value of the USERID property.</param>
        /// <param name="fIRSTNAME">Initial value of the FIRSTNAME property.</param>
        /// <param name="lASTNAME">Initial value of the LASTNAME property.</param>
        public static Synapse_Security_User CreateSynapse_Security_User(global::System.Int64 id, global::System.String uSERID, global::System.String fIRSTNAME, global::System.String lASTNAME)
        {
            Synapse_Security_User synapse_Security_User = new Synapse_Security_User();
            synapse_Security_User.ID = id;
            synapse_Security_User.USERID = uSERID;
            synapse_Security_User.FIRSTNAME = fIRSTNAME;
            synapse_Security_User.LASTNAME = lASTNAME;
            return synapse_Security_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIRSTNAME
        {
            get
            {
                return _FIRSTNAME;
            }
            set
            {
                OnFIRSTNAMEChanging(value);
                ReportPropertyChanging("FIRSTNAME");
                _FIRSTNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIRSTNAME");
                OnFIRSTNAMEChanged();
            }
        }
        private global::System.String _FIRSTNAME;
        partial void OnFIRSTNAMEChanging(global::System.String value);
        partial void OnFIRSTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LASTNAME
        {
            get
            {
                return _LASTNAME;
            }
            set
            {
                OnLASTNAMEChanging(value);
                ReportPropertyChanging("LASTNAME");
                _LASTNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LASTNAME");
                OnLASTNAMEChanged();
            }
        }
        private global::System.String _LASTNAME;
        partial void OnLASTNAMEChanging(global::System.String value);
        partial void OnLASTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CULTURE
        {
            get
            {
                return _CULTURE;
            }
            set
            {
                OnCULTUREChanging(value);
                ReportPropertyChanging("CULTURE");
                _CULTURE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CULTURE");
                OnCULTUREChanged();
            }
        }
        private global::System.String _CULTURE;
        partial void OnCULTUREChanging(global::System.String value);
        partial void OnCULTUREChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User_Profile")]
        public EntityCollection<Synapse_Security_User_Profile> Synapse_Security_User_Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Synapse_Security_User_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User_Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Synapse_Security_User_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User_Profile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Security_User_Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Security_User_Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Security_User_Profile object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fK_SECURITY_PROFILE">Initial value of the FK_SECURITY_PROFILE property.</param>
        /// <param name="fK_SECURITY_USER">Initial value of the FK_SECURITY_USER property.</param>
        public static Synapse_Security_User_Profile CreateSynapse_Security_User_Profile(global::System.Int64 id, global::System.Int64 fK_SECURITY_PROFILE, global::System.Int64 fK_SECURITY_USER)
        {
            Synapse_Security_User_Profile synapse_Security_User_Profile = new Synapse_Security_User_Profile();
            synapse_Security_User_Profile.ID = id;
            synapse_Security_User_Profile.FK_SECURITY_PROFILE = fK_SECURITY_PROFILE;
            synapse_Security_User_Profile.FK_SECURITY_USER = fK_SECURITY_USER;
            return synapse_Security_User_Profile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_SECURITY_PROFILE
        {
            get
            {
                return _FK_SECURITY_PROFILE;
            }
            set
            {
                OnFK_SECURITY_PROFILEChanging(value);
                ReportPropertyChanging("FK_SECURITY_PROFILE");
                _FK_SECURITY_PROFILE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_SECURITY_PROFILE");
                OnFK_SECURITY_PROFILEChanged();
            }
        }
        private global::System.Int64 _FK_SECURITY_PROFILE;
        partial void OnFK_SECURITY_PROFILEChanging(global::System.Int64 value);
        partial void OnFK_SECURITY_PROFILEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_SECURITY_USER
        {
            get
            {
                return _FK_SECURITY_USER;
            }
            set
            {
                OnFK_SECURITY_USERChanging(value);
                ReportPropertyChanging("FK_SECURITY_USER");
                _FK_SECURITY_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_SECURITY_USER");
                OnFK_SECURITY_USERChanged();
            }
        }
        private global::System.Int64 _FK_SECURITY_USER;
        partial void OnFK_SECURITY_USERChanging(global::System.Int64 value);
        partial void OnFK_SECURITY_USERChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_Profile")]
        public Synapse_Security_Profile Synapse_Security_Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_Profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_Profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Synapse_Security_Profile> Synapse_Security_ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Synapse_Security_Profile>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_Profile", "Synapse_Security_Profile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SYNAPSEModel", "FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User")]
        public Synapse_Security_User Synapse_Security_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_User>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_User>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Synapse_Security_User> Synapse_Security_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Synapse_Security_User>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Synapse_Security_User>("SYNAPSEModel.FK_Synapse_Security_User_Profile_Synapse_Security_User", "Synapse_Security_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Statistics")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Statistics : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Statistics object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="uSERID">Initial value of the USERID property.</param>
        /// <param name="fK_MODULE_ID">Initial value of the FK_MODULE_ID property.</param>
        /// <param name="fORMNAME">Initial value of the FORMNAME property.</param>
        /// <param name="oPEN_TIME">Initial value of the OPEN_TIME property.</param>
        /// <param name="cLOSE_TIME">Initial value of the CLOSE_TIME property.</param>
        /// <param name="aCTIVITY_TIME">Initial value of the ACTIVITY_TIME property.</param>
        /// <param name="oPENED_TIME">Initial value of the OPENED_TIME property.</param>
        public static Synapse_Statistics CreateSynapse_Statistics(global::System.Int64 id, global::System.String uSERID, global::System.Int64 fK_MODULE_ID, global::System.String fORMNAME, global::System.DateTime oPEN_TIME, global::System.DateTime cLOSE_TIME, global::System.Int64 aCTIVITY_TIME, global::System.Int64 oPENED_TIME)
        {
            Synapse_Statistics synapse_Statistics = new Synapse_Statistics();
            synapse_Statistics.ID = id;
            synapse_Statistics.USERID = uSERID;
            synapse_Statistics.FK_MODULE_ID = fK_MODULE_ID;
            synapse_Statistics.FORMNAME = fORMNAME;
            synapse_Statistics.OPEN_TIME = oPEN_TIME;
            synapse_Statistics.CLOSE_TIME = cLOSE_TIME;
            synapse_Statistics.ACTIVITY_TIME = aCTIVITY_TIME;
            synapse_Statistics.OPENED_TIME = oPENED_TIME;
            return synapse_Statistics;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                if (_USERID != value)
                {
                    OnUSERIDChanging(value);
                    ReportPropertyChanging("USERID");
                    _USERID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USERID");
                    OnUSERIDChanged();
                }
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_MODULE_ID
        {
            get
            {
                return _FK_MODULE_ID;
            }
            set
            {
                if (_FK_MODULE_ID != value)
                {
                    OnFK_MODULE_IDChanging(value);
                    ReportPropertyChanging("FK_MODULE_ID");
                    _FK_MODULE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FK_MODULE_ID");
                    OnFK_MODULE_IDChanged();
                }
            }
        }
        private global::System.Int64 _FK_MODULE_ID;
        partial void OnFK_MODULE_IDChanging(global::System.Int64 value);
        partial void OnFK_MODULE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FORMNAME
        {
            get
            {
                return _FORMNAME;
            }
            set
            {
                if (_FORMNAME != value)
                {
                    OnFORMNAMEChanging(value);
                    ReportPropertyChanging("FORMNAME");
                    _FORMNAME = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FORMNAME");
                    OnFORMNAMEChanged();
                }
            }
        }
        private global::System.String _FORMNAME;
        partial void OnFORMNAMEChanging(global::System.String value);
        partial void OnFORMNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OPEN_TIME
        {
            get
            {
                return _OPEN_TIME;
            }
            set
            {
                if (_OPEN_TIME != value)
                {
                    OnOPEN_TIMEChanging(value);
                    ReportPropertyChanging("OPEN_TIME");
                    _OPEN_TIME = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OPEN_TIME");
                    OnOPEN_TIMEChanged();
                }
            }
        }
        private global::System.DateTime _OPEN_TIME;
        partial void OnOPEN_TIMEChanging(global::System.DateTime value);
        partial void OnOPEN_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CLOSE_TIME
        {
            get
            {
                return _CLOSE_TIME;
            }
            set
            {
                if (_CLOSE_TIME != value)
                {
                    OnCLOSE_TIMEChanging(value);
                    ReportPropertyChanging("CLOSE_TIME");
                    _CLOSE_TIME = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CLOSE_TIME");
                    OnCLOSE_TIMEChanged();
                }
            }
        }
        private global::System.DateTime _CLOSE_TIME;
        partial void OnCLOSE_TIMEChanging(global::System.DateTime value);
        partial void OnCLOSE_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ACTIVITY_TIME
        {
            get
            {
                return _ACTIVITY_TIME;
            }
            set
            {
                if (_ACTIVITY_TIME != value)
                {
                    OnACTIVITY_TIMEChanging(value);
                    ReportPropertyChanging("ACTIVITY_TIME");
                    _ACTIVITY_TIME = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ACTIVITY_TIME");
                    OnACTIVITY_TIMEChanged();
                }
            }
        }
        private global::System.Int64 _ACTIVITY_TIME;
        partial void OnACTIVITY_TIMEChanging(global::System.Int64 value);
        partial void OnACTIVITY_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OPENED_TIME
        {
            get
            {
                return _OPENED_TIME;
            }
            set
            {
                if (_OPENED_TIME != value)
                {
                    OnOPENED_TIMEChanging(value);
                    ReportPropertyChanging("OPENED_TIME");
                    _OPENED_TIME = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OPENED_TIME");
                    OnOPENED_TIMEChanged();
                }
            }
        }
        private global::System.Int64 _OPENED_TIME;
        partial void OnOPENED_TIMEChanging(global::System.Int64 value);
        partial void OnOPENED_TIMEChanged();

        #endregion
    
    }

    #endregion
    
}
