//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ProofOfConcept
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SYNAPSEEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SYNAPSEEntities object using the connection string found in the 'SYNAPSEEntities' section of the application configuration file.
        /// </summary>
        public SYNAPSEEntities() : base("name=SYNAPSEEntities", "SYNAPSEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SYNAPSEEntities object.
        /// </summary>
        public SYNAPSEEntities(string connectionString) : base(connectionString, "SYNAPSEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SYNAPSEEntities object.
        /// </summary>
        public SYNAPSEEntities(EntityConnection connection) : base(connection, "SYNAPSEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Synapse_Security_User> Synapse_Security_User
        {
            get
            {
                if ((_Synapse_Security_User == null))
                {
                    _Synapse_Security_User = base.CreateObjectSet<Synapse_Security_User>("Synapse_Security_User");
                }
                return _Synapse_Security_User;
            }
        }
        private ObjectSet<Synapse_Security_User> _Synapse_Security_User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Synapse_Security_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSynapse_Security_User(Synapse_Security_User synapse_Security_User)
        {
            base.AddObject("Synapse_Security_User", synapse_Security_User);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SYNAPSEModel", Name="Synapse_Security_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Synapse_Security_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Synapse_Security_User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="uSERID">Initial value of the USERID property.</param>
        /// <param name="fIRSTNAME">Initial value of the FIRSTNAME property.</param>
        /// <param name="lASTNAME">Initial value of the LASTNAME property.</param>
        public static Synapse_Security_User CreateSynapse_Security_User(global::System.Int64 id, global::System.String uSERID, global::System.String fIRSTNAME, global::System.String lASTNAME)
        {
            Synapse_Security_User synapse_Security_User = new Synapse_Security_User();
            synapse_Security_User.ID = id;
            synapse_Security_User.USERID = uSERID;
            synapse_Security_User.FIRSTNAME = fIRSTNAME;
            synapse_Security_User.LASTNAME = lASTNAME;
            return synapse_Security_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIRSTNAME
        {
            get
            {
                return _FIRSTNAME;
            }
            set
            {
                OnFIRSTNAMEChanging(value);
                ReportPropertyChanging("FIRSTNAME");
                _FIRSTNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIRSTNAME");
                OnFIRSTNAMEChanged();
            }
        }
        private global::System.String _FIRSTNAME;
        partial void OnFIRSTNAMEChanging(global::System.String value);
        partial void OnFIRSTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LASTNAME
        {
            get
            {
                return _LASTNAME;
            }
            set
            {
                OnLASTNAMEChanging(value);
                ReportPropertyChanging("LASTNAME");
                _LASTNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LASTNAME");
                OnLASTNAMEChanged();
            }
        }
        private global::System.String _LASTNAME;
        partial void OnLASTNAMEChanging(global::System.String value);
        partial void OnLASTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CULTURE
        {
            get
            {
                return _CULTURE;
            }
            set
            {
                OnCULTUREChanging(value);
                ReportPropertyChanging("CULTURE");
                _CULTURE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CULTURE");
                OnCULTUREChanged();
            }
        }
        private global::System.String _CULTURE;
        partial void OnCULTUREChanging(global::System.String value);
        partial void OnCULTUREChanged();

        #endregion
    
    }

    #endregion
    
}
