//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CFNEducation_FormationEntities : DbContext
    {
        public CFNEducation_FormationEntities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education_Agent> Education_Agent { get; set; }
        public virtual DbSet<Education_Agent_Formation> Education_Agent_Formation { get; set; }
        public virtual DbSet<Education_AgentCertifElecFunc> Education_AgentCertifElecFunc { get; set; }
        public virtual DbSet<Education_AgentCertifElecOPP> Education_AgentCertifElecOPP { get; set; }

       
        public virtual DbSet<Education_AgentCertificatDivers> Education_AgentCertificatDivers { get; set; }
        public virtual DbSet<Education_AgentPassportBusiness> Education_AgentPassportBusiness { get; set; }
        public virtual DbSet<Education_AgentPassportDesign> Education_AgentPassportDesign { get; set; }
        public virtual DbSet<Education_AgentPassportSafety> Education_AgentPassportSafety { get; set; }
        public virtual DbSet<Education_AgentStatus> Education_AgentStatus { get; set; }
        public virtual DbSet<Education_CategorieFormation> Education_CategorieFormation { get; set; }
        public virtual DbSet<Education_CertifElecFunc> Education_CertifElecFunc { get; set; }
        public virtual DbSet<Education_CertifElecOPP> Education_CertifElecOPP { get; set; }
        public virtual DbSet<Education_CertificatDivers> Education_CertificatDivers { get; set; }
        public virtual DbSet<Education_Competence> Education_Competence { get; set; }
        public virtual DbSet<Education_CompetenceGroup> Education_CompetenceGroup { get; set; }
        public virtual DbSet<Education_CompetenceSubGroup> Education_CompetenceSubGroup { get; set; }
        public virtual DbSet<Education_Departement> Education_Departement { get; set; }
        public virtual DbSet<Education_Equipe> Education_Equipe { get; set; }
        public virtual DbSet<Education_Formation> Education_Formation { get; set; }
        public virtual DbSet<Education_FormationCategory> Education_FormationCategory { get; set; }
        public virtual DbSet<Education_FormationDossier> Education_FormationDossier { get; set; }
        public virtual DbSet<Education_FormationDossierType> Education_FormationDossierType { get; set; }
        public virtual DbSet<Education_FormationProvider> Education_FormationProvider { get; set; }
        public virtual DbSet<Education_FormationResultat> Education_FormationResultat { get; set; }
        public virtual DbSet<Education_FormationSession> Education_FormationSession { get; set; }
        public virtual DbSet<Education_Former> Education_Former { get; set; }
        public virtual DbSet<Education_Function> Education_Function { get; set; }
        public virtual DbSet<Education_GroupLearner> Education_GroupLearner { get; set; }
        public virtual DbSet<Education_GroupLearner_Agent> Education_GroupLearner_Agent { get; set; }
        public virtual DbSet<Education_Habilitation> Education_Habilitation { get; set; }
        public virtual DbSet<Education_InRoute> Education_InRoute { get; set; }
        public virtual DbSet<Education_Log> Education_Log { get; set; }
        public virtual DbSet<Education_Matrice> Education_Matrice { get; set; }
        public virtual DbSet<Education_Matrice_Agent> Education_Matrice_Agent { get; set; }
        public virtual DbSet<Education_Matrice_AgentEquivalence> Education_Matrice_AgentEquivalence { get; set; }
        public virtual DbSet<Education_Matrice_Formation> Education_Matrice_Formation { get; set; }
        public virtual DbSet<Education_Matrice_GrLearner> Education_Matrice_GrLearner { get; set; }
        public virtual DbSet<Education_MovementStep> Education_MovementStep { get; set; }
        public virtual DbSet<Education_MovementStepAgent> Education_MovementStepAgent { get; set; }
        public virtual DbSet<Education_MovementType> Education_MovementType { get; set; }
        public virtual DbSet<Education_PassportBusiness> Education_PassportBusiness { get; set; }
        public virtual DbSet<Education_PassportDesign> Education_PassportDesign { get; set; }
        public virtual DbSet<Education_PassportSafety> Education_PassportSafety { get; set; }
        public virtual DbSet<Education_PassportType> Education_PassportType { get; set; }
        public virtual DbSet<Education_Provider> Education_Provider { get; set; }
        public virtual DbSet<Education_ProviderContact> Education_ProviderContact { get; set; }
        public virtual DbSet<Education_Role> Education_Role { get; set; }
        public virtual DbSet<Education_RoleAstreinte> Education_RoleAstreinte { get; set; }
        public virtual DbSet<Education_RoleEPI> Education_RoleEPI { get; set; }
        public virtual DbSet<Education_Service> Education_Service { get; set; }
        public virtual DbSet<Education_SessionUnite> Education_SessionUnite { get; set; }
        public virtual DbSet<Education_UnitePrice> Education_UnitePrice { get; set; }
        public virtual DbSet<Education_MovementAgent> Education_MovementAgent { get; set; }
    
        public virtual ObjectResult<UpdateStatutMovementAgent_Result> UpdateStatutMovementAgent(Nullable<long> idAgent, Nullable<long> idType)
        {
            var idAgentParameter = idAgent.HasValue ?
                new ObjectParameter("IdAgent", idAgent) :
                new ObjectParameter("IdAgent", typeof(long));
    
            var idTypeParameter = idType.HasValue ?
                new ObjectParameter("IdType", idType) :
                new ObjectParameter("IdType", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateStatutMovementAgent_Result>("UpdateStatutMovementAgent", idAgentParameter, idTypeParameter);
        }
    }
}
