//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_MovementAgent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_MovementAgent()
        {
            this.Education_MovementStepAgent = new HashSet<Education_MovementStepAgent>();
        }
    
        public long Movement_Id { get; set; }
        public Nullable<long> MovementAgent_Type { get; set; }
        public Nullable<long> Movement_Agent { get; set; }
        public Nullable<long> Movement_Admin { get; set; }
        public Nullable<long> Movement_ServiceActual { get; set; }
        public Nullable<long> Movement_ServiceFutur { get; set; }
    
        public virtual Education_Agent Education_Agent { get; set; }
        public virtual Education_Agent Education_Agent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_MovementStepAgent> Education_MovementStepAgent { get; set; }
        public virtual Education_Service Education_Service { get; set; }
        public virtual Education_Service Education_Service1 { get; set; }
    }
}
