//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_AgentPassportBusiness
    {
        public long AgentPassportBusiness_Id { get; set; }
        public Nullable<System.DateTime> AgentPassportBusiness_SendingDate { get; set; }
        public Nullable<System.DateTime> AgentPassportBusiness_ReturnDate { get; set; }
        public Nullable<bool> AgentPassportBusiness_HierarchyCertification { get; set; }
        public string AgentPassportBusiness_Remark { get; set; }
        public Nullable<long> AgentPassportBusiness_Agent { get; set; }
        public Nullable<long> AgentPassportBusiness_Business { get; set; }
    
        public virtual Education_PassportBusiness Education_PassportBusiness { get; set; }
        public virtual Education_Agent Education_Agent { get; set; }
    }
}
