//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_AgentCertifElecOPP
    {
        public long AgentCertifElecOPP_Id { get; set; }
        public Nullable<System.DateTime> AgentCertifElecOPP_SendingDate { get; set; }
        public Nullable<System.DateTime> AgentCertifElecOPP_ReceivedDate { get; set; }
        public Nullable<bool> AgentCertifElecOPP_IsCertified { get; set; }
        public Nullable<System.DateTime> AgentCertifElecOPP_ValidityDate { get; set; }
        public string AgentCertifElecOPP_Remark { get; set; }
        public Nullable<long> AgentCertifElecOPP_Agent { get; set; }
        public Nullable<long> AgentCertifElecOPP_Certification { get; set; }
    
        public virtual Education_CertifElecOPP Education_CertifElecOPP { get; set; }
        public virtual Education_Agent Education_Agent { get; set; }
    }
}
