//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_CompetenceSubGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_CompetenceSubGroup()
        {
            this.Education_Competence = new HashSet<Education_Competence>();
        }
    
        public long CompetenceSubGroup_Id { get; set; }
        public string CompetenceSubGroup_Name { get; set; }
        public Nullable<long> CompetenceSubGroup_Group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_Competence> Education_Competence { get; set; }
        public virtual Education_CompetenceGroup Education_CompetenceGroup { get; set; }
    }
}
