//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_AgentPassportDesign
    {
        public long AgentPassportDesign_Id { get; set; }
        public Nullable<System.DateTime> AgentPassportDesign_SendingDate { get; set; }
        public Nullable<System.DateTime> AgentPassportDesign_ReceivedDate { get; set; }
        public Nullable<bool> AgentPassportDesign_IsCertified { get; set; }
        public string AgentPassportDesign_Remark { get; set; }
        public Nullable<long> AgentPassportDesign_Agent { get; set; }
        public Nullable<long> AgentPassportDesign_Passport { get; set; }
    
        public virtual Education_Agent Education_Agent { get; set; }
        public virtual Education_PassportDesign Education_PassportDesign { get; set; }
    }
}
