//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_FormationResultat
    {
        public long FormationResultat_Id { get; set; }
        public Nullable<long> FormationResultat_Formation { get; set; }
        public Nullable<double> FormationResultat_Resultat { get; set; }
        public Nullable<int> FormationResultat_Year { get; set; }
    
        public virtual Education_Formation Education_Formation { get; set; }
    }
}
