//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_AgentPassportSafety
    {
        public long AgentPassportSafety_Id { get; set; }
        public Nullable<long> AgentPassportSafety_Agent { get; set; }
        public Nullable<int> AgentPassportSafety_LevelPS { get; set; }
        public Nullable<System.DateTime> AgentPassportSafety_SendingDate { get; set; }
        public Nullable<System.DateTime> AgentPassportSafety_ReturnDate { get; set; }
        public Nullable<bool> AgentPassportSafety_HierarchyCertification { get; set; }
        public string AgentPassportSafety_Remarks { get; set; }
        public string AgentPassportSafety_PayRemarks { get; set; }
        public Nullable<long> AgentPassportSafety_Passport { get; set; }
    
        public virtual Education_PassportSafety Education_PassportSafety { get; set; }
        public virtual Education_Agent Education_Agent { get; set; }
    }
}
