//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_FormationSession
    {
        public long FormationSession_Id { get; set; }
        public long FormationSession_Formation { get; set; }
        public Nullable<int> FormationSession_Year { get; set; }
        public Nullable<int> FormationSession_NumberOfSessions { get; set; }
        public Nullable<long> FormationSession_Unite { get; set; }
    
        public virtual Education_Formation Education_Formation { get; set; }
        public virtual Education_SessionUnite Education_SessionUnite { get; set; }
    }
}
