//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_CategorieFormation
    {
        public long CategorieFormation_Id { get; set; }
        public string CategorieFormation_Name { get; set; }
        public Nullable<long> CategorieFormation_Formation { get; set; }
    
        public virtual Education_Formation Education_Formation { get; set; }
    }
}
