//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Matrice_Formation
    {
        public long MatriceFormation_Id { get; set; }
        public Nullable<long> MatriceFormation_Formation { get; set; }
        public Nullable<long> MatriceFormation_Matrice { get; set; }
        public Nullable<int> MatriceFormation_Recurrency { get; set; }
    
        public virtual Education_Formation Education_Formation { get; set; }
        public virtual Education_Matrice Education_Matrice { get; set; }
    }
}
