//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_FormationDossier
    {
        public long FormationDossier_Id { get; set; }
        public Nullable<long> FormationDossier_Formation { get; set; }
        public string FormationDossier_InfoFiche { get; set; }
        public string FormationDossier_InfoFicheHyperLink { get; set; }
        public Nullable<System.DateTime> FormationDossier_DateUpdate { get; set; }
        public string FormationDossier_ReasonOfUpdate { get; set; }
        public string FormationDossier_Remarks { get; set; }
        public string FormationDossier_Priority { get; set; }
        public Nullable<long> FormationDossier_TypeDossier { get; set; }
        public Nullable<bool> FormationDossier_Hubbel { get; set; }
        public string FormationDossier_Syllabus { get; set; }
        public string FormationDossier_SyllabusHyperLink { get; set; }
        public Nullable<bool> FormationDossier_InOrder { get; set; }
        public Nullable<bool> FormationDossier_Scenario { get; set; }
    
        public virtual Education_FormationDossierType Education_FormationDossierType { get; set; }
        public virtual Education_Formation Education_Formation { get; set; }
    }
}
