//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Matrice_AgentEquivalence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_Matrice_AgentEquivalence()
        {
            this.Education_Matrice_Agent = new HashSet<Education_Matrice_Agent>();
        }
    
        public long MatriceAgentEquivalence_Id { get; set; }
        public Nullable<long> MatriceAgentEquivalence_Formation { get; set; }
        public string MatriceAgentEquivalence_Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_Matrice_Agent> Education_Matrice_Agent { get; set; }
    }
}
