//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Matrice_Agent
    {
        public long MatriceAgent_Id { get; set; }
        public Nullable<long> MatriceAgent_Agent { get; set; }
        public Nullable<long> MatriceAgent_MatriceFormation { get; set; }
        public Nullable<System.DateTime> MatriceAgent_DateFormationAttented { get; set; }
        public Nullable<bool> MatriceAgent_IsAttented { get; set; }
        public Nullable<bool> MatriceAgent_HasEquivalence { get; set; }
        public Nullable<long> MatriceAgent_Equivalence { get; set; }
    
        public virtual Education_Agent Education_Agent { get; set; }
        public virtual Education_Matrice_AgentEquivalence Education_Matrice_AgentEquivalence { get; set; }
        public virtual Education_Matrice_Formation Education_Matrice_Formation { get; set; }
    }
}
