//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_MovementStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_MovementStep()
        {
            this.Education_MovementStepAgent = new HashSet<Education_MovementStepAgent>();
        }
    
        public long MovementStep_Id { get; set; }
        public string MovementStep_Intitule { get; set; }
        public Nullable<long> MovementStep_Type { get; set; }
    
        public virtual Education_MovementType Education_MovementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_MovementStepAgent> Education_MovementStepAgent { get; set; }
    }
}
