//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Competence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_Competence()
        {
            this.Education_Formation = new HashSet<Education_Formation>();
        }
    
        public long Competence_Id { get; set; }
        public string Competence_Name { get; set; }
        public Nullable<long> Competence_Group { get; set; }
        public string Competence_Description { get; set; }
    
        public virtual Education_CompetenceSubGroup Education_CompetenceSubGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_Formation> Education_Formation { get; set; }
    }
}
