//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Former
    {
        public long Former_Id { get; set; }
        public string Former_FullName { get; set; }
        public string Former_PhoneNumber { get; set; }
        public string Former_Email { get; set; }
        public string Former_CountryOrigin { get; set; }
        public string Former_Material { get; set; }
        public string Former_ContactPhoneNumber { get; set; }
        public string Former_ContactFullName { get; set; }
        public string Former_ContactEmail { get; set; }
        public string Former_Remarks { get; set; }
        public string Former_FormerAccess { get; set; }
        public string Former_CodePO { get; set; }
        public string Former_Vendor { get; set; }
        public string Former_ResMaster4 { get; set; }
        public string Former_ResMaster5 { get; set; }
        public Nullable<long> Former_Provider { get; set; }
    
        public virtual Education_Provider Education_Provider { get; set; }
    }
}
