//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Equipe
    {
        public long Equipe_Id { get; set; }
        public Nullable<long> Equipe_Service { get; set; }
        public string Equipe_Name { get; set; }
    
        public virtual Education_Service Education_Service { get; set; }
    }
}
