//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Log
    {
        public long Log_Id { get; set; }
        public string Log_Message { get; set; }
        public string Log_Stacktrace { get; set; }
        public string Log_Source { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public string Log_Type { get; set; }
    }
}
