//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_PassportBusiness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_PassportBusiness()
        {
            this.Education_AgentPassportBusiness = new HashSet<Education_AgentPassportBusiness>();
        }
    
        public long PassportBusiness_Id { get; set; }
        public string PassportBusiness_Name { get; set; }
        public Nullable<bool> PassportBusiness_Actif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_AgentPassportBusiness> Education_AgentPassportBusiness { get; set; }
    }
}
