//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_CertificatDivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education_CertificatDivers()
        {
            this.Education_AgentCertificatDivers = new HashSet<Education_AgentCertificatDivers>();
        }
    
        public long CertificatDivers_Id { get; set; }
        public string CertificatDivers_Name { get; set; }
        public Nullable<bool> CertificatDivers_Actif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_AgentCertificatDivers> Education_AgentCertificatDivers { get; set; }
    }
}
