//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_Agent_Formation
    {
        public long AgentFormation_Id { get; set; }
        public long AgentFormation_Agent { get; set; }
        public long AgentFormation_Formation { get; set; }
    
        public virtual Education_Agent Education_Agent { get; set; }
        public virtual Education_Formation Education_Formation { get; set; }
    }
}
