//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_GroupLearner_Agent
    {
        public long GroupLearnerAgent_Id { get; set; }
        public long GroupLearnerAgent_Agent { get; set; }
        public long GroupLearnerAgent_GroupeLearner { get; set; }
    
        public virtual Education_GroupLearner Education_GroupLearner { get; set; }
        public virtual Education_Agent Education_Agent { get; set; }
    }
}
