//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynapseCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynapseCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Border {
            get {
                object obj = ResourceManager.GetObject("Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Border1 {
            get {
                object obj = ResourceManager.GetObject("Border1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseHot {
            get {
                object obj = ResourceManager.GetObject("CloseHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClosePressed {
            get {
                object obj = ResourceManager.GetObject("ClosePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running a development version. This version is only for test purpose.
        /// </summary>
        internal static string EN_DevelopmentMode {
            get {
                return ResourceManager.GetString("EN_DevelopmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is inactive for maintenance, please try again later.
        /// </summary>
        internal static string EN_Maintenance {
            get {
                return ResourceManager.GetString("EN_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but you have no access to this module\nPlease Request access before....
        /// </summary>
        internal static string EN_NoAccess {
            get {
                return ResourceManager.GetString("EN_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Module version is not up to date please start it via the portal to update it.
        /// </summary>
        internal static string EN_UpdateNeeded {
            get {
                return ResourceManager.GetString("EN_UpdateNeeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterAdd {
            get {
                object obj = ResourceManager.GetObject("FilterAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilterDelete {
            get {
                object obj = ResourceManager.GetObject("FilterDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous exécutez une version de developpement. Celle-ci est uniquement destinée aux tests..
        /// </summary>
        internal static string FR_DevelopmentMode {
            get {
                return ResourceManager.GetString("FR_DevelopmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce module est inactif pour des raisons de maintenance,Veuillez réessayer plus tard..
        /// </summary>
        internal static string FR_Maintenance {
            get {
                return ResourceManager.GetString("FR_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas accès à ce module.\nVeuillez demander les accès avant l&apos;exécution de celui-ci....
        /// </summary>
        internal static string FR_NoAccess {
            get {
                return ResourceManager.GetString("FR_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La version de ce module n&apos;est plus à jour,Veuillez le lancer via le portail..
        /// </summary>
        internal static string FR_UpdateNeeded {
            get {
                return ResourceManager.GetString("FR_UpdateNeeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maximize {
            get {
                object obj = ResourceManager.GetObject("Maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaximizeDisabled {
            get {
                object obj = ResourceManager.GetObject("MaximizeDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaximizeHot {
            get {
                object obj = ResourceManager.GetObject("MaximizeHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaximizePressed {
            get {
                object obj = ResourceManager.GetObject("MaximizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MinimizeDisabled {
            get {
                object obj = ResourceManager.GetObject("MinimizeDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MinimizeHot {
            get {
                object obj = ResourceManager.GetObject("MinimizeHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MinimizePressed {
            get {
                object obj = ResourceManager.GetObject("MinimizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U werkt in een ontwikkelingsomgeving met een test versie..
        /// </summary>
        internal static string NL_DevelopmentMode {
            get {
                return ResourceManager.GetString("NL_DevelopmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door onderhoud is deze module niet actief. Gelieve later opnieuw te proberen..
        /// </summary>
        internal static string NL_Maintenance {
            get {
                return ResourceManager.GetString("NL_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry maar u hebt geen toegang tot deze module. Gelieve een aanvraag in te dienen..
        /// </summary>
        internal static string NL_NoAccess {
            get {
                return ResourceManager.GetString("NL_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze module versie is nu verouderd. Om de laatste versie op te laden dient u deze module via de portaal op te starten ..
        /// </summary>
        internal static string NL_UpdateNeeded {
            get {
                return ResourceManager.GetString("NL_UpdateNeeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print_Grid_32 {
            get {
                object obj = ResourceManager.GetObject("Print_Grid_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Restore {
            get {
                object obj = ResourceManager.GetObject("Restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreDisabled {
            get {
                object obj = ResourceManager.GetObject("RestoreDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreHot {
            get {
                object obj = ResourceManager.GetObject("RestoreHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestorePressed {
            get {
                object obj = ResourceManager.GetObject("RestorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search2 {
            get {
                object obj = ResourceManager.GetObject("search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewRestore {
            get {
                object obj = ResourceManager.GetObject("ViewRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewSave {
            get {
                object obj = ResourceManager.GetObject("ViewSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
