//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_ADR.PMADRService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
    public partial class FunctionalError : AbstractException {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnicalError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionalError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplicationError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
    public abstract partial class AbstractException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string objectTypeField;
        
        private string objectKeyField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private string rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
                this.RaisePropertyChanged("ObjectType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ObjectKey {
            get {
                return this.objectKeyField;
            }
            set {
                this.objectKeyField = value;
                this.RaisePropertyChanged("ObjectKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
                this.RaisePropertyChanged("LogNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
                this.RaisePropertyChanged("LogMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
                this.RaisePropertyChanged("MessageV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
                this.RaisePropertyChanged("MessageV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
                this.RaisePropertyChanged("MessageV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
                this.RaisePropertyChanged("MessageV4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("Parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("System");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class OrderDataO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberField;
        
        private string orderDescriptionField;
        
        private string functionalLocationField;
        
        private string mainWorkCenterField;
        
        private string revisionField;
        
        private string basicStartDateField;
        
        private string basicFinishDateField;
        
        private string ultimateExecutionDateField;
        
        private string riskLevelField;
        
        private string maintenancePlanField;
        
        private string maintenanceItemField;
        
        private string workCenterField;
        
        private string revisionPhaseField;
        
        private string zPPartnerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrderDescription {
            get {
                return this.orderDescriptionField;
            }
            set {
                this.orderDescriptionField = value;
                this.RaisePropertyChanged("OrderDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FunctionalLocation {
            get {
                return this.functionalLocationField;
            }
            set {
                this.functionalLocationField = value;
                this.RaisePropertyChanged("FunctionalLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MainWorkCenter {
            get {
                return this.mainWorkCenterField;
            }
            set {
                this.mainWorkCenterField = value;
                this.RaisePropertyChanged("MainWorkCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BasicStartDate {
            get {
                return this.basicStartDateField;
            }
            set {
                this.basicStartDateField = value;
                this.RaisePropertyChanged("BasicStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BasicFinishDate {
            get {
                return this.basicFinishDateField;
            }
            set {
                this.basicFinishDateField = value;
                this.RaisePropertyChanged("BasicFinishDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string UltimateExecutionDate {
            get {
                return this.ultimateExecutionDateField;
            }
            set {
                this.ultimateExecutionDateField = value;
                this.RaisePropertyChanged("UltimateExecutionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string RiskLevel {
            get {
                return this.riskLevelField;
            }
            set {
                this.riskLevelField = value;
                this.RaisePropertyChanged("RiskLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MaintenancePlan {
            get {
                return this.maintenancePlanField;
            }
            set {
                this.maintenancePlanField = value;
                this.RaisePropertyChanged("MaintenancePlan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MaintenanceItem {
            get {
                return this.maintenanceItemField;
            }
            set {
                this.maintenanceItemField = value;
                this.RaisePropertyChanged("MaintenanceItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string WorkCenter {
            get {
                return this.workCenterField;
            }
            set {
                this.workCenterField = value;
                this.RaisePropertyChanged("WorkCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string RevisionPhase {
            get {
                return this.revisionPhaseField;
            }
            set {
                this.revisionPhaseField = value;
                this.RaisePropertyChanged("RevisionPhase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZPPartnerName {
            get {
                return this.zPPartnerNameField;
            }
            set {
                this.zPPartnerNameField = value;
                this.RaisePropertyChanged("ZPPartnerName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/")]
    public partial class GetOrderdetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrderDataO[] orderDetailsFindResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public OrderDataO[] OrderDetailsFindResponse {
            get {
                return this.orderDetailsFindResponseField;
            }
            set {
                this.orderDetailsFindResponseField = value;
                this.RaisePropertyChanged("OrderDetailsFindResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class OrderDataI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mainWorkCenterField;
        
        private string riskLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MainWorkCenter {
            get {
                return this.mainWorkCenterField;
            }
            set {
                this.mainWorkCenterField = value;
                this.RaisePropertyChanged("MainWorkCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RiskLevel {
            get {
                return this.riskLevelField;
            }
            set {
                this.riskLevelField = value;
                this.RaisePropertyChanged("RiskLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class Channel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Application applicationField;
        
        private Profile profileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Application Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
                this.RaisePropertyChanged("Application");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Profile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
                this.RaisePropertyChanged("Profile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Enumerations/")]
    public enum Application {
        
        /// <remarks/>
        ECWA,
        
        /// <remarks/>
        EMS_TOOLING,
        
        /// <remarks/>
        ADR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Enumerations/")]
    public enum Profile {
        
        /// <remarks/>
        EBL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class OperationCallData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private string userIDField;
        
        private string languageField;
        
        private string sessionIDField;
        
        private string correlationIDField;
        
        private System.DateTime operationTimeStampField;
        
        private bool operationTimeStampFieldSpecified;
        
        private Channel channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
                this.RaisePropertyChanged("CorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime OperationTimeStamp {
            get {
                return this.operationTimeStampField;
            }
            set {
                this.operationTimeStampField = value;
                this.RaisePropertyChanged("OperationTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationTimeStampSpecified {
            get {
                return this.operationTimeStampFieldSpecified;
            }
            set {
                this.operationTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("OperationTimeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Channel Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("Channel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/")]
    public partial class GetOrderdetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OperationCallData operationCallDataField;
        
        private OrderDataI[] inputDataOrderdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperationCallData OperationCallData {
            get {
                return this.operationCallDataField;
            }
            set {
                this.operationCallDataField = value;
                this.RaisePropertyChanged("OperationCallData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public OrderDataI[] InputDataOrderdetails {
            get {
                return this.inputDataOrderdetailsField;
            }
            set {
                this.inputDataOrderdetailsField = value;
                this.RaisePropertyChanged("InputDataOrderdetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
    public partial class TimeOut : AbstractException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
    public partial class TechnicalError : AbstractException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
    public partial class ApplicationError : AbstractException {
        
        private Exception[] exceptionListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Exception[] ExceptionList {
            get {
                return this.exceptionListField;
            }
            set {
                this.exceptionListField = value;
                this.RaisePropertyChanged("ExceptionList");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", ConfigurationName="PMADRService.PMADRSERVICEPort")]
    public interface PMADRSERVICEPort {
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetOrderdetails n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Module_ADR.PMADRService.FunctionalError), Action="", Name="FunctionalError", Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(Module_ADR.PMADRService.TechnicalError), Action="", Name="TechnicalError", Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractException))]
        Module_ADR.PMADRService.GetOrderdetailsResponse1 GetOrderdetails(Module_ADR.PMADRService.GetOrderdetails1 request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetOrderattachment n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Module_ADR.PMADRService.FunctionalError), Action="", Name="FunctionalError", Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(Module_ADR.PMADRService.TechnicalError), Action="", Name="TechnicalError", Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractException))]
        Module_ADR.PMADRService.GetOrderattachmentResponse1 GetOrderattachment(Module_ADR.PMADRService.GetOrderattachment1 request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération GetMPItemattachment n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Module_ADR.PMADRService.FunctionalError), Action="", Name="FunctionalError", Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(Module_ADR.PMADRService.TechnicalError), Action="", Name="TechnicalError", Namespace="http://www.electrabel.com/p-i/20190703/Faults/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractException))]
        Module_ADR.PMADRService.GetMPItemattachmentResponse1 GetMPItemattachment(Module_ADR.PMADRService.GetMPItemattachment1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderdetails1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", Order=0)]
        public Module_ADR.PMADRService.GetOrderdetails GetOrderdetails;
        
        public GetOrderdetails1() {
        }
        
        public GetOrderdetails1(Module_ADR.PMADRService.GetOrderdetails GetOrderdetails) {
            this.GetOrderdetails = GetOrderdetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderdetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", Order=0)]
        public Module_ADR.PMADRService.GetOrderdetailsResponse GetOrderdetailsResponse;
        
        public GetOrderdetailsResponse1() {
        }
        
        public GetOrderdetailsResponse1(Module_ADR.PMADRService.GetOrderdetailsResponse GetOrderdetailsResponse) {
            this.GetOrderdetailsResponse = GetOrderdetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/")]
    public partial class GetOrderattachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OperationCallData operationCallDataField;
        
        private CreateAttachment[] inputDataAttachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperationCallData OperationCallData {
            get {
                return this.operationCallDataField;
            }
            set {
                this.operationCallDataField = value;
                this.RaisePropertyChanged("OperationCallData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CreateAttachment[] InputDataAttachment {
            get {
                return this.inputDataAttachmentField;
            }
            set {
                this.inputDataAttachmentField = value;
                this.RaisePropertyChanged("InputDataAttachment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class CreateAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Attachment[] attachmentField;
        
        private string orderNumberField;
        
        private string userIDField;
        
        private string sTETimeField;
        
        private string sTETextField;
        
        private string sTEOffField;
        
        private string pPTextField;
        
        private string pPOffField;
        
        private string rICTextField;
        
        private string rICOffField;
        
        private string aQTextField;
        
        private string aQOffField;
        
        private string iSTextField;
        
        private string iSOffField;
        
        private string rPTextField;
        
        private string rPOffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Attachment[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string STETime {
            get {
                return this.sTETimeField;
            }
            set {
                this.sTETimeField = value;
                this.RaisePropertyChanged("STETime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STEText {
            get {
                return this.sTETextField;
            }
            set {
                this.sTETextField = value;
                this.RaisePropertyChanged("STEText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STEOff {
            get {
                return this.sTEOffField;
            }
            set {
                this.sTEOffField = value;
                this.RaisePropertyChanged("STEOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PPText {
            get {
                return this.pPTextField;
            }
            set {
                this.pPTextField = value;
                this.RaisePropertyChanged("PPText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PPOff {
            get {
                return this.pPOffField;
            }
            set {
                this.pPOffField = value;
                this.RaisePropertyChanged("PPOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string RICText {
            get {
                return this.rICTextField;
            }
            set {
                this.rICTextField = value;
                this.RaisePropertyChanged("RICText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string RICOff {
            get {
                return this.rICOffField;
            }
            set {
                this.rICOffField = value;
                this.RaisePropertyChanged("RICOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string AQText {
            get {
                return this.aQTextField;
            }
            set {
                this.aQTextField = value;
                this.RaisePropertyChanged("AQText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AQOff {
            get {
                return this.aQOffField;
            }
            set {
                this.aQOffField = value;
                this.RaisePropertyChanged("AQOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ISText {
            get {
                return this.iSTextField;
            }
            set {
                this.iSTextField = value;
                this.RaisePropertyChanged("ISText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ISOff {
            get {
                return this.iSOffField;
            }
            set {
                this.iSOffField = value;
                this.RaisePropertyChanged("ISOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string RPText {
            get {
                return this.rPTextField;
            }
            set {
                this.rPTextField = value;
                this.RaisePropertyChanged("RPText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string RPOff {
            get {
                return this.rPOffField;
            }
            set {
                this.rPOffField = value;
                this.RaisePropertyChanged("RPOff");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class Attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string contentField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/")]
    public partial class GetOrderattachmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttchMessage[] orderAttachmentFindResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AttchMessage[] OrderAttachmentFindResponse {
            get {
                return this.orderAttachmentFindResponseField;
            }
            set {
                this.orderAttachmentFindResponseField = value;
                this.RaisePropertyChanged("OrderAttachmentFindResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class AttchMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ackMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AckMessage {
            get {
                return this.ackMessageField;
            }
            set {
                this.ackMessageField = value;
                this.RaisePropertyChanged("AckMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderattachment1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", Order=0)]
        public Module_ADR.PMADRService.GetOrderattachment GetOrderattachment;
        
        public GetOrderattachment1() {
        }
        
        public GetOrderattachment1(Module_ADR.PMADRService.GetOrderattachment GetOrderattachment) {
            this.GetOrderattachment = GetOrderattachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderattachmentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", Order=0)]
        public Module_ADR.PMADRService.GetOrderattachmentResponse GetOrderattachmentResponse;
        
        public GetOrderattachmentResponse1() {
        }
        
        public GetOrderattachmentResponse1(Module_ADR.PMADRService.GetOrderattachmentResponse GetOrderattachmentResponse) {
            this.GetOrderattachmentResponse = GetOrderattachmentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/")]
    public partial class GetMPItemattachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OperationCallData operationCallDataField;
        
        private CreateMPIAttachment[] inputMPIAttachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperationCallData OperationCallData {
            get {
                return this.operationCallDataField;
            }
            set {
                this.operationCallDataField = value;
                this.RaisePropertyChanged("OperationCallData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CreateMPIAttachment[] InputMPIAttachment {
            get {
                return this.inputMPIAttachmentField;
            }
            set {
                this.inputMPIAttachmentField = value;
                this.RaisePropertyChanged("InputMPIAttachment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/Types/")]
    public partial class CreateMPIAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Attachment[] attachmentField;
        
        private string maintenanceItemField;
        
        private string userIDField;
        
        private string riskLevelField;
        
        private string sTETimeField;
        
        private string sTETextField;
        
        private string sTEOffField;
        
        private string pPTextField;
        
        private string pPOffField;
        
        private string rICTextField;
        
        private string rICOffField;
        
        private string aQTextField;
        
        private string aQOffField;
        
        private string iSTextField;
        
        private string iSOffField;
        
        private string rPTextField;
        
        private string rPOffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Attachment[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MaintenanceItem {
            get {
                return this.maintenanceItemField;
            }
            set {
                this.maintenanceItemField = value;
                this.RaisePropertyChanged("MaintenanceItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RiskLevel {
            get {
                return this.riskLevelField;
            }
            set {
                this.riskLevelField = value;
                this.RaisePropertyChanged("RiskLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STETime {
            get {
                return this.sTETimeField;
            }
            set {
                this.sTETimeField = value;
                this.RaisePropertyChanged("STETime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STEText {
            get {
                return this.sTETextField;
            }
            set {
                this.sTETextField = value;
                this.RaisePropertyChanged("STEText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string STEOff {
            get {
                return this.sTEOffField;
            }
            set {
                this.sTEOffField = value;
                this.RaisePropertyChanged("STEOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PPText {
            get {
                return this.pPTextField;
            }
            set {
                this.pPTextField = value;
                this.RaisePropertyChanged("PPText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PPOff {
            get {
                return this.pPOffField;
            }
            set {
                this.pPOffField = value;
                this.RaisePropertyChanged("PPOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string RICText {
            get {
                return this.rICTextField;
            }
            set {
                this.rICTextField = value;
                this.RaisePropertyChanged("RICText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string RICOff {
            get {
                return this.rICOffField;
            }
            set {
                this.rICOffField = value;
                this.RaisePropertyChanged("RICOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AQText {
            get {
                return this.aQTextField;
            }
            set {
                this.aQTextField = value;
                this.RaisePropertyChanged("AQText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string AQOff {
            get {
                return this.aQOffField;
            }
            set {
                this.aQOffField = value;
                this.RaisePropertyChanged("AQOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ISText {
            get {
                return this.iSTextField;
            }
            set {
                this.iSTextField = value;
                this.RaisePropertyChanged("ISText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ISOff {
            get {
                return this.iSOffField;
            }
            set {
                this.iSOffField = value;
                this.RaisePropertyChanged("ISOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string RPText {
            get {
                return this.rPTextField;
            }
            set {
                this.rPTextField = value;
                this.RaisePropertyChanged("RPText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string RPOff {
            get {
                return this.rPOffField;
            }
            set {
                this.rPOffField = value;
                this.RaisePropertyChanged("RPOff");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/")]
    public partial class GetMPItemattachmentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttchMessage[] mPIAttachmentFindResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AttchMessage[] MPIAttachmentFindResponse {
            get {
                return this.mPIAttachmentFindResponseField;
            }
            set {
                this.mPIAttachmentFindResponseField = value;
                this.RaisePropertyChanged("MPIAttachmentFindResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMPItemattachment1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", Order=0)]
        public Module_ADR.PMADRService.GetMPItemattachment GetMPItemattachment;
        
        public GetMPItemattachment1() {
        }
        
        public GetMPItemattachment1(Module_ADR.PMADRService.GetMPItemattachment GetMPItemattachment) {
            this.GetMPItemattachment = GetMPItemattachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMPItemattachmentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.electrabel.com/p-i/20190703/PMADRSERVICE/", Order=0)]
        public Module_ADR.PMADRService.GetMPItemattachmentResponse GetMPItemattachmentResponse;
        
        public GetMPItemattachmentResponse1() {
        }
        
        public GetMPItemattachmentResponse1(Module_ADR.PMADRService.GetMPItemattachmentResponse GetMPItemattachmentResponse) {
            this.GetMPItemattachmentResponse = GetMPItemattachmentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PMADRSERVICEPortChannel : Module_ADR.PMADRService.PMADRSERVICEPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMADRSERVICEPortClient : System.ServiceModel.ClientBase<Module_ADR.PMADRService.PMADRSERVICEPort>, Module_ADR.PMADRService.PMADRSERVICEPort {
        
        public PMADRSERVICEPortClient() {
        }
        
        public PMADRSERVICEPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMADRSERVICEPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMADRSERVICEPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMADRSERVICEPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Module_ADR.PMADRService.GetOrderdetailsResponse1 Module_ADR.PMADRService.PMADRSERVICEPort.GetOrderdetails(Module_ADR.PMADRService.GetOrderdetails1 request) {
            return base.Channel.GetOrderdetails(request);
        }
        
        public Module_ADR.PMADRService.GetOrderdetailsResponse GetOrderdetails(Module_ADR.PMADRService.GetOrderdetails GetOrderdetails1) {
            Module_ADR.PMADRService.GetOrderdetails1 inValue = new Module_ADR.PMADRService.GetOrderdetails1();
            inValue.GetOrderdetails = GetOrderdetails1;
            Module_ADR.PMADRService.GetOrderdetailsResponse1 retVal = ((Module_ADR.PMADRService.PMADRSERVICEPort)(this)).GetOrderdetails(inValue);
            return retVal.GetOrderdetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Module_ADR.PMADRService.GetOrderattachmentResponse1 Module_ADR.PMADRService.PMADRSERVICEPort.GetOrderattachment(Module_ADR.PMADRService.GetOrderattachment1 request) {
            return base.Channel.GetOrderattachment(request);
        }
        
        public Module_ADR.PMADRService.GetOrderattachmentResponse GetOrderattachment(Module_ADR.PMADRService.GetOrderattachment GetOrderattachment1) {
            Module_ADR.PMADRService.GetOrderattachment1 inValue = new Module_ADR.PMADRService.GetOrderattachment1();
            inValue.GetOrderattachment = GetOrderattachment1;
            Module_ADR.PMADRService.GetOrderattachmentResponse1 retVal = ((Module_ADR.PMADRService.PMADRSERVICEPort)(this)).GetOrderattachment(inValue);
            return retVal.GetOrderattachmentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Module_ADR.PMADRService.GetMPItemattachmentResponse1 Module_ADR.PMADRService.PMADRSERVICEPort.GetMPItemattachment(Module_ADR.PMADRService.GetMPItemattachment1 request) {
            return base.Channel.GetMPItemattachment(request);
        }
        
        public Module_ADR.PMADRService.GetMPItemattachmentResponse GetMPItemattachment(Module_ADR.PMADRService.GetMPItemattachment GetMPItemattachment1) {
            Module_ADR.PMADRService.GetMPItemattachment1 inValue = new Module_ADR.PMADRService.GetMPItemattachment1();
            inValue.GetMPItemattachment = GetMPItemattachment1;
            Module_ADR.PMADRService.GetMPItemattachmentResponse1 retVal = ((Module_ADR.PMADRService.PMADRSERVICEPort)(this)).GetMPItemattachment(inValue);
            return retVal.GetMPItemattachmentResponse;
        }
    }
}
